--PARTE I

IF DB_ID('EmpresaSQL') IS NOT NULL
BEGIN
ALTER DATABASE EmpresaSQL
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE EmpresaSQL;
END
GO

CREATE DATABASE EmpresaSQL;
Go

USE EmpresaSQL;
Go

CREATE TABLE TDepartamentos (
nDepartamentoID INT IDENTITY(1,1),
cNombreDepartamento NVARCHAR(100) UNIQUE NOT NULL,
CONSTRAINT PK_DepartamentoID PRIMARY KEY (nDepartamentoID),
CONSTRAINT Uq_NombreDepartamento UNIQUE (cNombreDepartamento)
);

CREATE TABLE TCargo (
nCargoID INT IDENTITY(1,1),
cNombreCargo NVARCHAR(100) UNIQUE NOT NULL,
CONSTRAINT PK_nCargoID PRIMARY KEY (nCargoID),
CONSTRAINT Uq_NombreCargo UNIQUE (cNombreCargo)
);

CREATE TABLE TEmpleado(
nEmpleadoID INT IDENTITY(1,1),
cNIF VARCHAR(12) UNIQUE NOT NULL,
cNombre NVARCHAR(80) NOT NULL,
cApellido NVARCHAR(80) NOT NULL,
nDepartamentoID INT,
nCargoID INT,
dFechaContratacion DATETIME DEFAULT GETDATE(),
nSalario DECIMAL (10,2),
CONSTRAINT PK_nEmpleadoID PRIMARY KEY (nEmpleadoID),
CONSTRAINT Uq_cNIF UNIQUE (cNIF),
CONSTRAINT FK_nDepartamentoID FOREIGN KEY (nDepartamentoID) REFERENCES TDepartamentos(nDepartamentoID),
CONSTRAINT FK_nCargoID FOREIGN KEY (nCargoID) REFERENCES Tcargo(nCargoID),
CONSTRAINT CK_nSalario CHECK (nSalario >= 300)
);

CREATE TABLE TProyecto (
nProyectoID INT IDENTITY(1,1),
cNombreProyecto NVARCHAR(120) UNIQUE NOT NULL,
dFechaInicio DATETIME NOT NULL,
dFechaFinalizacion DATETIME NOT NULL,
CONSTRAINT PK_nProyectoID PRIMARY KEY (nProyectoID)
)

CREATE TABLE TEmpleadoProyecto (
nEmpleadoProyecto INT IDENTITY(1,1),
nEmpleadoID INT,
nProyectoID INT,
CONSTRAINT PK_EmpleadoProyecto PRIMARY KEY (nEmpleadoProyecto),
CONSTRAINT FK_nEmpleadoID FOREIGN KEY (nEmpleadoID) REFERENCES TEmpleado(nEmpleadoID),
CONSTRAINT FK_nProyectoID FOREIGN KEY (nProyectoID) REFERENCES TProyecto(nProyectoID)
);

--PARTE II
ALTER TABLE TEmpleado ADD cEmail NVARCHAR(26);
ALTER TABLE TEmpleado ADD cTelefono VARCHAR(9);
ALTER TABLE TEmpleado ALTER COLUMN cNombre NVARCHAR(100);
ALTER TABLE TEmpleado  ALTER COLUMN cApellido NVARCHAR(100);
ALTER TABLE TEmpleado ADD cDireccion NVARCHAR(MAX);
ALTER TABLE TEmpleado ADD nEdad INT;
ALTER TABLE TEmpleado ADD CONSTRAINT CK_Edad CHECK (nEdad >+




