IF DB_ID('EmpresaSQL') IS NOT NULL
BEGIN
ALTER DATABASE EmpresaSQL
SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE EmpresaSQL;
END
GO



CREATE DATABASE EmpresaSQL;
Go

USE EmpresaSQL;
Go



CREATE TABLE TDepartamentos (
nDepartamentoID INT IDENTITY(1,1) NOT NULL,
cNombreDepartamento NVARCHAR(100) UNIQUE NOT NULL,
CONSTRAINT PK_DepartamentoID PRIMARY KEY (nDepartamentoID),
CONSTRAINT Uq_NombreDepartamento UNIQUE (cNombreDepartamento)
);

CREATE TABLE TCargo (
nCargoID INT IDENTITY(1,1) NOT NULL,
cNombreCargo NVARCHAR(100) UNIQUE NOT NULL,
CONSTRAINT PK_nCargoID PRIMARY KEY (nCargoID),
CONSTRAINT Uq_NombreCargo UNIQUE (cNombreCargo)
);

CREATE TABLE TEmpleado(
nEmpleadoID INT IDENTITY(1,1) NOT NULL,
cNIF VARCHAR(12) UNIQUE NOT NULL,
cNombre NVARCHAR(80) NOT NULL,
cApellido NVARCHAR(80) NOT NULL,
nDepartamentoID INT,
nCargoID INT,
dFechaContratacion DATETIME DEFAULT GETDATE(),
nSalario DECIMAL (10,2)
);